Initial support for Pascal syntax
decompme/decomp.me pull request #1399
Opened 2024-12-16 06:58 UTC by LLONSIT

- This PR adds minimal support for the Pascal language to mostly highlight some keywords and types.
- Note that this was mostly implemented to support SGI Pascal (the Pascal extension that IDO uses) and not common modern dialects like Free Pascal or Delphi.

2024-12-16 07:13 UTC, ethteck approved these changes

2024-12-19 22:53 UTC, bates64 requested changes
Otherwise, LGTM

2024-12-19 22:53 UTC, bates64 commented on frontend/src/lib/codemirror/pascal.js
> +/* Based on @codemirror/laegacy-modes/pascasl */
```suggestion
/* Based on @codemirror/legacy-modes/pascal */
```

2024-12-19 22:58 UTC, LLONSIT commented on frontend/src/lib/codemirror/pascal.js
> +/* Based on @codemirror/laegacy-modes/pascasl */
Oops

2024-12-19 23:39 UTC, merged