Add NDS (arm9) as a platform
decompme/decomp.me pull request #273
Opened 2021-12-31 14:46 UTC by mkst

2021-12-31 14:50 UTC, nanaian requested changes

2021-12-31 14:50 UTC, nanaian commented on frontend/src/components/PlatformSelect/nds.svg
> +<!-- Created with Inkscape (http://www.inkscape.org/) -->
'Save As' this SVG as an "Optimised SVG" pls

2021-12-31 14:50 UTC, nanaian commented on frontend/src/components/PlatformSelect/nds.svg
> +   height="32"
And also remove the width and height properties as in https://github.com/decompme/decomp.me/commit/ca46e243bdc3ecc02bb2f71a9adea33b502345d1

2022-01-01 09:05 UTC, ethteck approved these changes

2022-01-01 11:22 UTC, nanaian approved these changes

2022-01-01 11:25 UTC, merged