[WIP] Add Mac OS X platform and compilers
decompme/decomp.me pull request #462
Opened 2022-06-03 12:48 UTC by ChrisNonyminus

2022-06-03 12:54 UTC, ChrisNonyminus commented
https://commons.wikimedia.org/wiki/File:Tiger-like-x.svg
This is the logo's page. It's in the public domain.

2022-06-03 12:55 UTC, ChrisNonyminus commented
I should probably add it to the credits page though, yeah.

2022-06-03 12:59 UTC, ChrisNonyminus commented
![image](https://user-images.githubusercontent.com/50080567/171858582-592318a9-4e53-4200-9fc2-4dc59380a23d.png)
Right, sorry, I didn't realize you asked for a screenshot of the decomp.me site. I thought you meant to link to the source of the svg. I'm dumb :P

2022-06-03 13:01 UTC, ethteck commented
np :). and hmmm I wonder why we're getting 3, 4, 2 platforms per row. without dummy I wonder what it'll look like..

2022-06-03 13:02 UTC, ChrisNonyminus commented
Without dummy it looks like this.
![image](https://user-images.githubusercontent.com/50080567/171859105-14f3ce66-8e7c-450d-b87d-2fa9e59a5264.png)

2022-06-03 13:11 UTC, ethteck commented
I'd also add a unit test that confirms a compilation works (like you did for the os 9 PR) if you don't mind

2022-06-05 20:46 UTC, ethteck requested changes

2022-06-05 20:46 UTC, ethteck commented on backend/compilers/download.py
> +        log_name="convert_gas_syntax.py",
I don't think we should be re-downloading this file a bunch of times. We should be able to download it once and then copy it

2022-06-05 22:06 UTC, merged