Adding IDO 6.0
decompme/decomp.me pull request #674
Opened 2023-02-07 03:46 UTC by LLONSIT

2023-02-07 09:27 UTC, nanaian commented
black is failing

2023-02-07 13:27 UTC, LLONSIT commented
Qemu-irix with binfmt seems to be working

2023-02-07 13:57 UTC, ethteck commented
To echo what I said in the discord - black just wanted you to add a space after the # in your comment, so no need to delete the line entirely.

Additionally, we can't accept this PR as-is because the setting up of the compiler needs to happen in download.py rather than in the ci build script. You'll need to migrate the setup steps so any consumer of the repo can properly run the compiler.

2023-02-08 19:46 UTC, LLONSIT commented
Just need the qemu-irix command for the docker

2023-02-16 14:04 UTC, ethteck requested changes
Some more thing I found. @mkst @EllipticEllipsis could you two also review the most recent state of this, since I think you both have useful input probably (re: docker, re: changing the default flag for IDO 5.3 Pascal, respectively, along with anything else you see)

2023-02-16 14:04 UTC, ethteck commented on .github/workflows/ci.yml
> +          #ls /ido_root
could you remove this debugging line?

2023-02-16 14:04 UTC, ethteck commented on .github/workflows/ci.yml
> +            -e RUNNING_IN_DOCKER=1\
hard-coding this to 1 here seems wrong

2023-02-16 14:04 UTC, ethteck commented on .github/workflows/ci.yml
> +            decompme_backend -c 'echo $QEMU_LD_PREFIX && echo $RUNNING_IN_DOCKER && cd /decomp.me/backend && \
I think this is a debugging line and can be removed

2023-02-16 14:19 UTC, LLONSIT reviewed
Ok

2023-02-16 16:22 UTC, EllipticEllipsis commented
Given that most of 5.3 seems to use -mips1, it's probably sensible to change it (although I wish it had been mentioned in the PR description).

Could you try and get IDO 6.0 working with a fork of recomp? It shouldn't be too difficult if it's O32 and you don't need many manual hacks (most of them are for `copt`, which hopefully you don't need for this!). And it'd be a lot more convenient than qemu if it does work.

2023-02-21 06:55 UTC, ethteck commented
As mentioned in Discord, I think the way to go forward here is what EllipticEllipsis said above. I don't think adding all these dependencies and new requirements to CI / docker / any new host is a good idea for these compilers which will realistically only ever be used on the site by one or two people. If you're willing to put some effort into debugging the issues with ido recomp, I'm sure we can figure out a way to get these binaries working under that process. Until then, I'm going to close this, since I don't think it's appropriate for the site in its current form.

Please do feel free to raise another PR with your new AeroGauge JP Kiosk Demo preset and change to IDO 5.3 Pascal compiler flags if you'd like in the meantime.

2023-02-21 06:55 UTC, closed without merging